//! ICM (Infinite Context Memory) integration.
//! Auto-generates ICM context chunks from active scopes so tag-scoped memory
//! crosses scope boundaries.

use crate::scope::ActiveScopes;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use tracing;

/// Path to the ICM state file within state_dir.
fn icm_state_path(state_dir: &Path) -> PathBuf {
    state_dir.join("icm.json")
}

/// Stored ICM tag/bundle memory.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
struct IcmMemory {
    tags: Vec<String>,
    bundles: Vec<String>,
}

/// Generate an ICM context chunk encoding the active tags/bundles.
/// The chunk is formatted as a markdown block that agents can paste into ICM.
///
/// # Example output
/// ```text
/// ## llmenv context
/// Active scope: `work-vpn`, `rust`
/// Bundles: `bundle1`, `bundle2`
///
/// Use this when storing scope-specific memory in ICM:
/// - Store under keyword: `llmenv-tag:work-vpn`
/// - Memory will be retrieved in any project using tag `work-vpn`
/// ```
pub fn generate_context_chunk(active: &ActiveScopes, bundles: &[String]) -> String {
    let tags_str = if active.tags.is_empty() {
        "(none)".to_string()
    } else {
        active
            .tags
            .iter()
            .map(|t| format!("`{}`", t))
            .collect::<Vec<_>>()
            .join(", ")
    };

    let bundles_str = if bundles.is_empty() {
        "(none)".to_string()
    } else {
        bundles
            .iter()
            .map(|b| format!("`{}`", b))
            .collect::<Vec<_>>()
            .join(", ")
    };

    format!(
        "## llmenv context\n\
         Active tags: {}\n\
         Bundles: {}\n\n\
         Store scope-specific memory under keyword `llmenv-tag:<tag>` \
         so it is retrievable across projects.",
        tags_str, bundles_str
    )
}

/// Store tag/bundle memory mappings for retrieval by SessionStart hook.
/// Called during `llmenv export` to record which tags and bundles are active,
/// so the SessionStart hook can inject them into agent context via ICM.
///
/// # Errors
/// Returns an error if memory storage fails.
pub fn store_tag_memory(active: &ActiveScopes, bundles: &[String]) -> anyhow::Result<()> {
    let state_dir = crate::paths::state_dir()?;
    fs::create_dir_all(&state_dir)?;

    let memory = IcmMemory {
        tags: active.tags.iter().cloned().collect::<Vec<_>>(),
        bundles: bundles.to_vec(),
    };

    let path = icm_state_path(&state_dir);
    let json = serde_json::to_string(&memory)?;
    fs::write(path, json)?;

    tracing::debug!(
        "stored ICM tag memory: tags={}, bundles={}",
        memory.tags.join(","),
        memory.bundles.join(",")
    );
    Ok(())
}

/// Generate ICM context chunk for SessionStart hook to inject tag/bundle mappings.
/// This hook runs at agent startup and retrieves stored tag mappings so agents
/// can access tag-scoped memory using `llmenv-tag:<tag>` keywords.
///
/// # Errors
/// Returns an error if memory retrieval fails.
pub fn recall_tag_memory_hook() -> anyhow::Result<String> {
    let chunk = "## llmenv tag-scoped memory\n\
                 This context was auto-generated by the llmenv SessionStart hook.\n\
                 Store scope-specific memory using keywords:\n\
                 - `llmenv-tag:<tag>` for tag-scoped memory\n\
                 - `llmenv-bundle:<bundle>` for bundle-scoped memory\n\n\
                 Memory stored with these keywords will be retrieved across projects \
                 when the same tags/bundles are active.";

    Ok(chunk.to_string())
}

/// Recall the last stored tag/bundle memory.
/// Used internally by tests to verify persistence.
///
/// # Errors
/// Returns an error if memory retrieval fails.
#[cfg(test)]
fn recall_stored_tag_memory() -> anyhow::Result<String> {
    let state_dir = crate::paths::state_dir()?;
    let path = icm_state_path(&state_dir);

    if !path.exists() {
        return Ok(String::new());
    }

    let json = fs::read_to_string(path)?;
    let memory: IcmMemory = serde_json::from_str(&json)?;

    let tags_str = if memory.tags.is_empty() {
        "no tags".to_string()
    } else {
        memory.tags.join(", ")
    };

    let bundles_str = if memory.bundles.is_empty() {
        "no bundles".to_string()
    } else {
        memory.bundles.join(", ")
    };

    Ok(format!("tags: {}, bundles: {}", tags_str, bundles_str))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn test_context_chunk_includes_tags() {
        let mut tags = BTreeSet::new();
        tags.insert("work-vpn".to_string());
        tags.insert("rust".to_string());

        let active = ActiveScopes {
            scopes: vec![],
            tags,
        };

        let chunk = generate_context_chunk(&active, &[]);
        assert!(chunk.contains("work-vpn"));
        assert!(chunk.contains("rust"));
        assert!(chunk.contains("llmenv-tag"));
    }

    #[test]
    fn test_context_chunk_handles_no_tags() {
        let active = ActiveScopes::default();
        let chunk = generate_context_chunk(&active, &[]);
        assert!(chunk.contains("(none)"));
    }

    #[test]
    fn test_context_chunk_includes_bundles() {
        let active = ActiveScopes::default();
        let bundles = vec!["bundle1".to_string(), "bundle2".to_string()];
        let chunk = generate_context_chunk(&active, &bundles);
        assert!(chunk.contains("bundle1"));
        assert!(chunk.contains("bundle2"));
    }

    #[test]
    fn test_store_tag_memory_succeeds() {
        let mut tags = BTreeSet::new();
        tags.insert("work".to_string());
        tags.insert("rust".to_string());

        let active = ActiveScopes {
            scopes: vec![],
            tags,
        };

        let bundles = vec!["bundle1".to_string(), "bundle2".to_string()];
        let result = store_tag_memory(&active, &bundles);
        assert!(result.is_ok());
    }

    #[test]
    fn test_recall_tag_memory_hook_generates_markdown() {
        let result = recall_tag_memory_hook();
        assert!(result.is_ok());

        let content = result.unwrap();
        assert!(content.contains("llmenv-tag"));
        assert!(content.contains("keyword"));
    }

    #[test]
    fn test_store_tag_memory_persists_to_icm() {
        use std::env;
        let temp_dir = tempfile::TempDir::new().unwrap();
        unsafe {
            env::set_var("LLMENV_STATE_DIR", temp_dir.path());
        }

        let mut tags = BTreeSet::new();
        tags.insert("work".to_string());
        tags.insert("rust".to_string());

        let active = ActiveScopes {
            scopes: vec![],
            tags,
        };

        let bundles = vec!["backend".to_string()];
        let result = store_tag_memory(&active, &bundles);
        assert!(result.is_ok());

        // Verify the memory was actually stored by checking for a marker file
        // or by recalling and verifying content matches what was stored
        let recalled = recall_stored_tag_memory();
        assert!(recalled.is_ok());

        let content = recalled.unwrap();
        assert!(content.contains("work"));
        assert!(content.contains("rust"));
        assert!(content.contains("backend"));
    }
}
